version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt
